---
- hosts: all
  name: Harden Debian Image
  become: yes
  vars:
    # Set this to prevent interpreter discovery warnings.
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Wait for system to become ready
      wait_for:
        timeout: 30
      delegate_to: localhost

    - name: Wait for apt-get lock to be released
      shell: "while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done"
      become: yes
      changed_when: false
      failed_when: false
      register: result
      until: result.rc == 0

    - name: Update apt cache and install jq
      apt:
        name: jq
        state: present
        update_cache: yes

    - name: Download Google Cloud Ops Agent install script
      get_url:
        url: https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
        dest: /tmp/add-google-cloud-ops-agent-repo.sh
        mode: '0755'

    - name: Install Google Cloud Ops Agent
      command: /tmp/add-google-cloud-ops-agent-repo.sh --also-install
      args:
        creates: /etc/google-cloud-ops-agent/config.yaml

    - name: Set ulimit permanently for all users
      copy:
        dest: /etc/security/limits.d/99-packer.conf
        content: |
          * soft nofile 64000
          * hard nofile 64000