---
- hosts: all
  vars:
    ansible_python_interpreter: /opt/venv/bin/python3
- name: Harden Debian Image
  hosts: all
  become: yes
  tasks:
    - name: Wait for system to become ready
      wait_for:
        timeout: 30
      delegate_to: localhost

    - name: Update apt cache and install jq
      apt:
        name: jq
        state: present
        update_cache: yes

    - name: Download Google Cloud Ops Agent install script
      get_url:
        url: https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
        dest: /tmp/add-google-cloud-ops-agent-repo.sh
        mode: '0755'

    - name: Install Google Cloud Ops Agent
      command: /tmp/add-google-cloud-ops-agent-repo.sh --also-install
      args:
        creates: /etc/google-cloud-ops-agent/config.yaml

    - name: Set ulimit permanently for all users
      copy:
        dest: /etc/security/limits.d/99-packer.conf
        content: |
          * soft nofile 64000
          * hard nofile 64000
