---
- hosts: all
  name: Install MySQL Server
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install MariaDB Server (MySQL compatible)
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes