---
- hosts: all
  name: Configure Pet Shop Database
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure MySQL service is started
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Import the database schema
      ansible.builtin.shell:
        cmd: "mysql -u root < /tmp/db_schema.sql"
      args:
        # Upload the schema file before executing the command.
        # This assumes the schema file is in the 'website/db' directory.
        creates: /var/lib/mysql/petshop
      vars:
        ansible_ssh_transfer_method: scp