---
- hosts: all
  name: Configure Pet Shop Database
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure MySQL service is started
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Copy database schema to remote host
      ansible.builtin.copy:
        src: ../website/db/db_schema.sql
        dest: /tmp/db_schema.sql

    - name: Import the database schema
      ansible.builtin.shell:
        cmd: "mysql -u root < /tmp/db_schema.sql"
      args:
        # This task is idempotent because it only runs if the 'petshop' database doesn't exist.
        creates: /var/lib/mysql/petshop